-- Your SQL goes here
CREATE TABLE posts (
  id UUID PRIMARY KEY,
  name VARCHAR NOT NULL,
  note VARCHAR NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);